Grafana dashboards for kube-prometheus
cloudposse/grafana-dashboards pull request #1
Opened 2018-08-30 09:31 UTC by goruha

## What
* Fetch dashboards from https://github.com/coreos/prometheus-operator/tree/master/helm/grafana/dashboards

## Why
* Files in https://github.com/coreos/prometheus-operator/tree/master/helm/grafana/dashboards have wrong format that can not be imported by https://github.com/helm/charts/tree/master/stable/grafana

2018-08-30 14:46 UTC, aknysh commented on Makefile
> +## Write chamber secrets for agent
should we update the comments to make them more specific?
and the comments are the same for both Make targets.

2018-08-30 14:47 UTC, aknysh reviewed
see comments

2018-08-30 21:55 UTC, osterman commented on Makefile
> +apply: kube-prometheus/apply nginx/apply
I think `import` would be a more apropos target name as we are importing and then transforming (but not loading) the dashboards.

2018-09-04 19:28 UTC, osterman requested changes
Update to use `README.yaml`

Add references section for chart and helmfile

2018-09-05 19:57 UTC, aknysh commented on README.yaml
> +  Grafana dashboards imported from open source projects and proccessed to be imported with grafana dashboard provisioner.
Don't use `import` two times?
Grafana dashboards taken from open source projects ...

2018-09-05 19:57 UTC, aknysh commented on README.yaml
> +  Starting from [Grafana 5.0](http://docs.grafana.org/administration/provisioning/#dashboards) there is provisioning
Starting with [Grafana 5.0](http://docs.grafana.org/administration/provisioning/#dashboards) there is a provisioning system that uses config files to create/update dashboards.

2018-09-05 19:58 UTC, aknysh commented on README.yaml
> +  This project is about workaround for the problem.
This project is a workaround for the problem

2018-09-05 19:59 UTC, aknysh commented on README.yaml
> +  It fetch dashboard files and process them replacing `${DS_PROMETHEUS}` with `Prometheus` value and save it.
It fetches dashboard files and processes them replacing `${DS_PROMETHEUS}` with `Prometheus`, and then saves it

2018-09-05 20:00 UTC, aknysh commented on README.yaml
> +  Processed dashboards files are commited into the repo, so you can provision them by putting the files into grafana
commited. Misspelling of committed :)
https://en.wiktionary.org/wiki/commited

2018-09-05 20:01 UTC, aknysh commented on README.yaml
> +  Current supported dashboards:
Currently supported dashboards

2018-09-05 20:02 UTC, aknysh commented on README.yaml
> +  provisioner dashboards directory. __Required existed prometheus datasource named `Prometheus`__
__Requires existing Prometheus datasource named `Prometheus`__

2018-09-05 20:02 UTC, aknysh commented on README.yaml
> +  Config grafana provisioner following [instructions](http://docs.grafana.org/administration/provisioning/#dashboards)
Config Grafana provisioner by following these [instructions]

2018-09-05 20:04 UTC, aknysh commented on README.yaml
> +    description: "Example provisioning the dashboards with stable grafana chart."
Example of provisioning

2018-09-05 20:05 UTC, aknysh commented on README.yaml
> +    description: "Complete documentation for the Cloud Posse solution"
Complete documentation for the Cloud Posse solutions

2018-09-05 20:05 UTC, aknysh reviewed
see comments

2018-09-05 20:11 UTC, goruha commented
@aknysh - Addressed comments

2018-09-05 20:37 UTC, aknysh approved these changes

2018-09-05 20:45 UTC, osterman approved these changes

2018-09-06 08:52 UTC, merged